### PR TITLE
Feature/sensor value error codes

### PR DESCRIPTION
**Pull request by sergio-rudenko**
-> Добавлены ErrorCodes (+ .schema) в спецификации датчиков
-> Добавлены LifeCycle уровни (+ .schema) в спецификации вендоров
----------
+ немного багфиксов

### CODE REVIEW

**Review by Dmitriy-U — COMMENTED** [review]
Super

**Comment by Dmitriy-U** [comment]
@sergio-rudenko would you add beta laboratories into specifications of outside vendors?

**Comment by ArtyomSkorobogatov** [comment]
@Dmitriy-U do you have rights for merge? Can you do it yourself?

**Comment by ArtyomSkorobogatov** [comment]
I'm just in the field without normal internet...

**Comment by Dmitriy-U** [comment]
@ArtyomSkorobogatov we will merge this branch int develop. Do not worry about it.

**Pull request merged**
